### Get posts
GET http://localhost:9090/social-media/users/3/posts

HTTP/1.1 200  - OK
content-type: application/json
connection: close
server: ballerina
date: Fri, 13 Jun 2025 10:17:16 +0530
content-encoding: gzip
content-length: 202